name: Selenium with Testing - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up JDK 20
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven

    # Step 3: Set BrowserStack Environment
    - name: Set BrowserStack Environment
      uses: browserstack/github-actions/setup-env@master
      with:
        username: mahmoudsameer_QCshyF
        access-key: xscrZZa7CFssqgRQgV16

    # Step 4: Start BrowserStack Local Tunnel
    - name: Start BrowserStack Local Tunnel
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: start
        local-identifier: selenium-test-local

    # Step 5: Install Allure CLI
    - name: Install Allure CLI
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
        tar -zxvf allure-2.24.0.tgz
        sudo mv allure-2.24.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    # Step 6: Build and Test with Maven
    - name: Build and Test with Maven
      env:
        BROWSERSTACK_USERNAME: mahmoudsameer_QCshyF
        BROWSERSTACK_ACCESS_KEY: xscrZZa7CFssqgRQgV16
      run: mvn clean test || echo "Tests failed, proceeding to generate reports."

    # Step 7: Ensure Allure Results Directory Exists
    - name: Ensure Allure Results Directory
      run: mkdir -p allure-results

    # Step 8: Generate Allure Report
    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report || echo "Failed to generate Allure Report."
      continue-on-error: true

    # Step 9: Upload Allure Report as Artifact
    - name: Upload Allure Report as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report

    # Step 10: Send Allure Report via Email
    - name: Send Allure Report via Email
      uses: dawidd6/action-send-mail@v3
      with:
        connection_url: smtp://smtp.gmail.com:587
        username: mahmoudsameer560@gmail.com
        password: blxi ymqn qjlk jpio
        to: mahmoudsameer560@gmail.com
        from: mahmoudsameer560@gmail.com
        subject: Allure Test Report
        body: |
          Please find the attached Allure Test Report.
        attachments: allure-report.zip

    # Step 11: Stop BrowserStack Local Tunnel
    - name: Stop BrowserStack Local Tunnel
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: stop

    # Step 12: Clean up Temporary Files
    - name: Clean up Temporary Files
      run: |
        rm -rf allure-2.24.0.tgz allure-2.24.0 allure-report.zip
