name: Selenium with Testing - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven

    - name: Install Allure CLI
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
        tar -zxvf allure-2.24.0.tgz
        sudo mv allure-2.24.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Set BrowserStack Credentials
      env:
        BROWSERSTACK_USERNAME: mahmoudsameer_QCshyF
        BROWSERSTACK_ACCESS_KEY: xscrZZa7CFssqgRQgV16
      run: |
        echo "BrowserStack credentials set."

    - name: Build and Test with Maven on BrowserStack
      env:
        BROWSERSTACK_USERNAME: mahmoudsameer_QCshyF
        BROWSERSTACK_ACCESS_KEY: xscrZZa7CFssqgRQgV16
      run: mvn clean test || echo "Tests failed but continuing to generate report"

    - name: Debug Allure Results Directory
      run: |
        echo "Listing allure-results directory contents:"
        ls -R allure-results

    - name: Ensure Allure Results Directory Exists
      run: mkdir -p allure-results

    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report || echo "Allure report generation failed"
      continue-on-error: true

    - name: Debug Allure Report Directory
      run: |
        echo "Listing allure-report directory contents:"
        ls -R allure-report

    - name: Upload Allure Report as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report

    - name: Zip Allure Results and Report
      run: |
        zip -r allure-report.zip allure-results allure-report

    - name: Send Allure Report via Email
      uses: dawidd6/action-send-mail@v3
      with:
        connection_url: smtp://smtp.gmail.com:587
        username: mahmoudsameer560@gmail.com
        password: blxi ymqn qjlk jpio
        to: mahmoudsameer560@gmail.com
        from: mahmoudsameer560@gmail.com
        subject: Allure Test Report
        body: Please find attached the Allure Test Report.
        attachments: allure-report.zip

    - name: Clean up Allure
      run: rm -rf allure-2.24.0.tgz allure-2.24.0
